services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: fpl
      POSTGRES_PASSWORD: fpl
      POSTGRES_DB: fpl_api_development
    ports:
      - "5433:5432"
    volumes:
      - fpl_pg_data:/var/lib/postgresql/data

volumes:
  fpl_pg_data:
